### ISSUE TITLE
Curl not found

### ISSUE THREAD

**Issue by lucibelloj** [ploner/RMixpanel#1]
`res <- mixpanelJQLQuery(account, jqlQuery) `
is resulting in the following error on PC only:

`Error in system(curlCall, intern = TRUE, ignore.stderr = TRUE) : 
  'curl' not found`

Tested and tried on multiple PCs and the full code stops there. Weirdly enough, the code works flawlessly on a Mac.

**Comment by ploner** [comment]
@lucibelloj, did you see this behaviour also with version 0.6-0?

**Comment by lucibelloj** [comment]
@ploner Behavior persists in version 0.6-0. 

The error seems to occur on PCs with multiple shared drives mounted running Windows 7. The error does not occur on non-shared drive computers on Windows 10. Would either of these discrepancies cause an issue?

**Comment by ploner** [comment]
Uh, honestly I have no Windows machine here to test. If you have time, you could try 'RCurl::getURL()' on your platforms. I think this is the command which does not work everywhere.

**Comment by lucibelloj** [comment]
It seems that the RCurl::getURL() exists and functions on a Windows machine? I cannot seem to get the script to run on a PC Machine.

Coincidently, on VMWare on a Mac running Windows, the script will run.

**Comment by ploner** [comment]
Hi,

maybe there are some other tools missing. Try installing devtools and/or
Rtools, see
https://www.rstudio.com/products/rpackages/devtools/
and pls tell me if it helped.

Thx
Meinhard

**Comment by lucibelloj** [comment]
Hi Meinhard, thanks for the tip. It looked like on a Windows computer you have to manually download the curl.exe file along with the security certificate and libcurl.dll and place it in the %windir% to allow the package to pull the data.

**Comment by ploner** [comment]
Uh, what an awful manual process :|
Thx for the informations!

**Comment by lucibelloj** [comment]
Awful but a solution now exists! Thanks for the awesome package!

**Comment by ploner** [comment]
Happy you can use it :)
