### ISSUE TITLE
Auth doesn't work with data.mixpanel.com

### ISSUE THREAD

**Issue by Serenthia** [ploner/RMixpanel#3]
As of this past week, I'm not able to authenticate data.mixpanel.com endpoints (ie. "export") with the secret in the URL.  Instead, it needs to be added as a Basic Auth header in the username.  I've verified this via curl.

https://github.com/ploner/RMixpanel/blob/45509e2a31b5fbabc4b6e7f2efd4ba34540b791f/R/mixpanelGetData.R#L14

**Comment by lawwu** [comment]
I'm also seeing this error in the latest version 0.6-2, but it works if you use 0.5-2

**Comment by mikeBohneTruth** [comment]
Mixpanel updated their API without notifying their users or changing the documentation. They told me after letting them know about these issues via email.
